name: Hello World App deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2   # For Python
      with:
        python-version: 3.x           # For Python

    - name: Install dependencies
      run: |
        # For Python
        pip install -r requirements.txt
    - name: Build and Deploy
      run: |
        # For Python
        python app.py

